import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useThemedStyles } from '../services/ThemeContext';

export default function BookingSuccessScreen({route,navigation}) {
  const styles=useThemedStyles(createStyles); const {booking}=route.params;
  return <View style={styles.container}><View style={styles.check}><Text style={styles.checkText}>✓</Text></View><Text style={styles.h1}>Booking Successful!</Text><Text style={styles.sub}>{booking.roomName} has been reserved.</Text><View style={styles.card}><Text style={styles.line}>📅 {booking.date}</Text><Text style={styles.line}>🕐 {booking.startTime} - {booking.endTime}</Text><Text style={styles.line}>📍 {booking.location}</Text><Text style={styles.id}>Booking ID: {booking.id}</Text></View><Pressable style={styles.button} onPress={()=>navigation.navigate('MainTabs',{screen:'Bookings'})}><Text style={styles.buttonText}>View My Bookings</Text></Pressable><Pressable onPress={()=>navigation.navigate('MainTabs',{screen:'Home'})}><Text style={styles.link}>Back Home</Text></Pressable></View>;
}
const createStyles=(colors)=>StyleSheet.create({container:{flex:1,backgroundColor:colors.background,alignItems:'center',justifyContent:'center',padding:24},check:{width:92,height:92,borderRadius:46,backgroundColor:colors.successSurface,alignItems:'center',justifyContent:'center'},checkText:{fontSize:52,color:colors.success,fontWeight:'900'},h1:{fontSize:28,fontWeight:'900',color:colors.text,marginTop:20},sub:{color:colors.muted,marginTop:8,textAlign:'center'},card:{width:'100%',backgroundColor:colors.card,padding:18,borderRadius:16,borderWidth:1,borderColor:colors.border,marginTop:24,gap:12},line:{color:colors.text,fontWeight:'600'},id:{color:colors.muted,fontSize:12,marginTop:4},button:{width:'100%',backgroundColor:colors.primary,padding:16,borderRadius:14,alignItems:'center',marginTop:22},buttonText:{color:colors.onPrimary,fontWeight:'900'},link:{color:colors.primaryDark,fontWeight:'800',marginTop:18}});
